### ISSUE TITLE
Add metadata to the website

### ISSUE THREAD

**Issue by maticbasle** [maticbasle/ColorSVG#20]
Add metadata to the website
http://ogp.me/

**Comment by JS-goose** [comment]
I'd be happy to tackle this one

**Comment by d5nguyen** [comment]
I'll check back. I'd be happy to help if help is still needed

**Comment by NitinNair89** [comment]
> 
> 
> Add metadata to the website
> http://ogp.me/

Do you want OpenGraph meta tags?
