### ISSUE TITLE
Create showcase graphic

### ISSUE THREAD

**Issue by maticbasle** [maticbasle/ColorSVG#28]
Create a new showcase graphic that will be linked to in the README file and in the website metadata.

Something similar to graphics that are made with this [tool](https://github.com/HackeSta/icons-promo-maker), but showcasing the different icons that ColorSVG has.

Text on the image should be:
> ColorSVG
> Customize your icons
> (icon graphics)
> (github icon) maticbasle/ColorSVG

**Comment by JMathis52** [comment]
I can work on this.
