### ISSUE TITLE
Text under arrows should show icon names

### ISSUE THREAD

**Issue by maticbasle** [maticbasle/ColorSVG#29]
The text under arrows to switch between icons should show full names of the icon not its ID.

Example of what I am referring to:
<img width="124" alt="screenshot 2018-10-26 at 21 33 54" src="https://user-images.githubusercontent.com/25509076/47588584-f24fae80-d966-11e8-89da-b51500fd758f.png">
(should be Visual Studio Code)

The names should not split into too many lines, arrows and text should be centered and can be moved closer inwards if needed.

**Comment by Yathousen** [comment]
Hi @maticbasle, i'll take a look at it.

**Comment by Yathousen** [comment]
@maticbasle should be resolve on this [pull request](https://github.com/maticbasle/ColorSVG/pull/30).
